<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [1]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
      
def factorial(n):
    import numpy as np
    arr=np.arange(1,n+1)
    return np.prod(arr)

factorial(4)


24

In [2]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    import numpy as np
    arr=np.arange(1,n+1)
    return np.cumprod(arr)

all_factorials(4)

array([ 1,  2,  6, 24], dtype=int32)

In [13]:
"""
Replace pass with the code that use ndarray, np.prod, and np.where 
to calculate the product of elements in array that are divisible by i

The function should take an array and an integer(i) as arguments and return an integer

"""
import numpy as np

def func(a,i):
    import numpy as np
    a1=a[np.where(a%i==0)]
    return np.prod(a1)
        
func(np.array([1,7,3,6]),3)

18

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [14]:
def get_pct_changes(file_name):
    import numpy as np
    #get data
    price=np.genfromtxt(file_name,delimiter=',',usecols=1)
    #remove the nan
    selector_array=(np.isnan(price)==False)
    price=price[selector_array]
    #calculate the pct change
    diff=np.diff(price)
    pricelist=list(price)
    pricelist.pop()
    price=np.array(pricelist)
    pct_change=diff/price
    return pct_change

In [15]:
get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, 'one-day percent change' to the file 
<li>Write a function that groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each groups in dataframe



In [1]:
datafile = "apple.csv"
import pandas as pd
df = pd.read_csv('apple.csv',na_values='null')
print(df)

            Date   Adj Close
0     1980-12-12    0.421597
1     1980-12-15    0.399601
2     1980-12-16    0.370272
3     1980-12-17    0.379437
4     1980-12-18    0.390436
...          ...         ...
9273  2017-09-20  156.070007
9274  2017-09-21  153.389999
9275  2017-09-22  151.889999
9276  2017-09-25  150.550003
9277  2017-09-26  153.139999

[9278 rows x 2 columns]


In [2]:
#Adds column 'one-day percent change'
df=df.copy()
df['one-day percent change']=df['Adj Close'].pct_change()
print(df)

            Date   Adj Close  one-day percent change
0     1980-12-12    0.421597                     NaN
1     1980-12-15    0.399601               -0.052173
2     1980-12-16    0.370272               -0.073396
3     1980-12-17    0.379437                0.024752
4     1980-12-18    0.390436                0.028988
...          ...         ...                     ...
9273  2017-09-20  156.070007               -0.016758
9274  2017-09-21  153.389999               -0.017172
9275  2017-09-22  151.889999               -0.009779
9276  2017-09-25  150.550003               -0.008822
9277  2017-09-26  153.139999                0.017204

[9278 rows x 3 columns]


In [9]:
def GroupColFunc(df1):
    import numpy as np
    import pandas as pd
    df1=df1.copy()
    df1=df1.iloc[1:]
    df1.reset_index(inplace = True, drop=True)
    df1['category']=0
    for i in df1.index:
        if df1.loc[i,'one-day percent change']>0.025:
            df1.loc[i,'category']='High+'
        elif 0<df1.loc[i,'one-day percent change']<=0.025:
            df1.loc[i,'category']='Low+'
        elif -0.025<=df1.loc[i,'one-day percent change']<0:
            df1.loc[i,'category']='Low-'
        elif df1.loc[i,'one-day percent change']<-0.025:
            df1.loc[i,'category']='High-'
    grouped_result=df1.groupby('category')['Adj Close','one-day percent change'].agg([np.size, np.mean])
    return grouped_result


In [10]:
#report size and mean
GroupColFunc(df)

C:\Users\lfh\AppData\Local\Temp\ipykernel_22652\3870347037.py:17: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grouped_result=df1.groupby('category')['Adj Close','one-day percent change'].agg([np.size, np.mean])


Adj Close            one-day percent change          
              size       mean                   size      mean
category                                                      
0              366   1.555968                    366  0.000000
High+         1391   8.652295                   1391  0.045705
High-         1210   8.289065                   1210 -0.044220
Low+          3170  26.292799                   3170  0.011020
Low-          3140  24.183470                   3140 -0.011171

Write a program that can choose decade and report the size and the mean of each group in dataframe
<li>Adds a column 'Decade' to the file (use first three numbers to be value of the decade ex. value for 1980-1989 is '198')  
<li>Write a function that have data from a file with decade column and decade as input
<li>Call function that you create in the first part to group the data
<li>Return dataframe of mean and size for each group of that decade

In [11]:
#adds column 'Decade'
df['Decade']=0
for i in df.index:
    df.loc[i,'Decade']=str(df.loc[i,'Date'])[:3]
print(df)

            Date   Adj Close  one-day percent change Decade
0     1980-12-12    0.421597                     NaN    198
1     1980-12-15    0.399601               -0.052173    198
2     1980-12-16    0.370272               -0.073396    198
3     1980-12-17    0.379437                0.024752    198
4     1980-12-18    0.390436                0.028988    198
...          ...         ...                     ...    ...
9273  2017-09-20  156.070007               -0.016758    201
9274  2017-09-21  153.389999               -0.017172    201
9275  2017-09-22  151.889999               -0.009779    201
9276  2017-09-25  150.550003               -0.008822    201
9277  2017-09-26  153.139999                0.017204    201

[9278 rows x 4 columns]


In [12]:
def report_decade(df2,decade):
    #Your code goes here
    result=df2[df2['Decade']==decade]
    return GroupColFunc(result)

In [13]:
#Test
report_decade(df,'198')

C:\Users\lfh\AppData\Local\Temp\ipykernel_22652\3870347037.py:17: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grouped_result=df1.groupby('category')['Adj Close','one-day percent change'].agg([np.size, np.mean])


Adj Close           one-day percent change          
              size      mean                   size      mean
category                                                     
0              193  0.619043                    193  0.000000
High+          404  0.607085                    404  0.046111
High-          350  0.582490                    350 -0.045644
Low+           657  0.725060                    657  0.012576
Low-           683  0.687610                    683 -0.012965